# 各種アイコン系
#  : E0BE
#  : E0BC
#  : E0B5
#  : E0B4
#  : E0BA
#  : E0B8
#  : E0B7
#  : E0B6
#  : E0BD
#  : E0BB
#  : E0BF
#  : E0B9
#  : E0B3
#  : E0B2
#  : E0B1
#  : E0B0
#  : EA9C
#  : F061
# 󰁔 : F0054
#  : F432
#  : E0D4
#  : E0D2
#  : E0D6
#  : E0D7
#  : E0C5
#  : E0C4
#  : E0C7
#  : E0C6
#  : E0CD
#  : E0CC
#  : E00A
#  : E009
#  : EF72
#  : F31B
#  : EBC9
#  : F31C
#  : E5FE
#  : F114
#  : EA83
#  : EAB2
#  : F00C
# 󰄬 : F012C
#  : F42E
#  : F45B
#  : F4EB
#  : E641
# 󱑀 : F1440
#  : F4BC
#  : EC19
#  : E266
# 󰘚 : F061A
#  : EfC5
#  : E702
# 󰊢 : F02A2
#  : E65D
#  : E61D
#  : E646
#  : E771
#  : E61E
#  : E649
#  : F12A
# 󰈅 : F0205
# ⚡
# 󰣇 : F08C7
#  : E732
#  : F303 

# 色のパレット設定
palette = 'mono'

# プロンプトのデザイン
format = """
[](fg:bg1)\
$os\
[](fg:bg1 bg:mid12)\
[](fg:mid12 bg:bg2)\
$username\
[](fg:bg2 bg:mid23)\
[](fg:mid23 bg:bg3)\
$directory\
[](fg:bg3)\
$fill\
$git_branch\
$git_status\
$fill\
[](fg:bg3)\
$status\
[](fg:mid23 bg:bg3)\
[](fg:bg2 bg:mid23)\
$cmd_duration\
[](fg:mid12 bg:bg2)\
[](fg:bg1 bg:mid12)\
$time\
[](fg:bg1)
$character\
"""

# $fill ~ $fill: each lang env component

right_format = """
$c
$cpp
"""

[fill]
symbol = '─'
style = "bold fg:bg_base"

[os]
format = '[$symbol]($style)'
style = "bold fg:fg1 bg:bg1"
disabled = false

[os.symbols]
Ubuntu = " "
EndeavourOS = "  "

[username]
format = '[ $user ]($style)'
style_user = "fg:fg2 bg:bg2"
show_always = true
disabled = false



[directory]
truncation_length = 2
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = "bold fg:fg3 bg:bg3"
truncation_symbol = '…/'

[git_branch]
symbol = '󰊢 '
truncation_length = 6
truncation_symbol = '…`'
style = 'fg:black bg:git'
format = '[](fg:git)[$symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:black bg:git'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘ '
format = '[ \[$all_status$ahead_behind \]]($style)[](fg:git)'

[character]
format = '$symbol'
success_symbol = "[ >> ](bold green)"
error_symbol = "[ >> ](bold red)"

[cmd_duration]
min_time = 5
format = '[  ]($style)[$duration ](bold $style)'
style = "fg:fg2 bg:bg2"
show_milliseconds = true

[time]
format = "[ $time]($style)"
style = "fg:fg1 bg:bg1"
disabled = false

[memory_usage]
format = "[ ${ram_pct}]($style)"
style = "bold fg:fg_mem bg:bg_mem"
threshold = -1
disabled = false

[jobs]
format = "[$symbol $number]($style)"
style = "bold fg:fg3 bg:bg3"
symbol = "✦"
symbol_threshold = 0
number_threshold = 1

[status]
format = "[ $symbol $common_meaming ]($style)"
style = "bold fg:fg3 bg:bg3"
disabled = false
symbol = "[✘](fg:red bg:bg3)"
success_symbol = "[](fg:green bg:bg3)"
sigint_symbol = "[⚡](fg:yellow bg:bg3)"
signal_symbol = "[](fg:red bg:bg3)" 

[shell]
disabled = false
style = "bold fg:fg2 bg:bg2"

[c]
format = "[  $name $version ]($style)"
style = "fg:cpp bg:black"
disabled = false

[cpp]
format = "[  $name $version ]($style)"
style = "fg:cpp bg:black"
disabled = false

[palettes.mono]
white = '#DFDFDF'
yellow = '#FFE100'
green = '#27C722'
red   = '#CF2727'
bg_base = '#404040'

fg1 = '#DFDFDF'
bg1 = '#101010'
mid12 = '#303030'
fg2 = '#000000'
bg2 = '#505050'
mid23 = '#707070'
fg3 = '#202020'
bg3 = '#909090'
fg_cmd = '#202020'
bg_cmd = '#909090'
mid_cmd_mem = '#505050'
fg_mem = '#DFDFDF'
bg_mem = '#202020'

right_accent = '#EB8900'
git = '#3261E6'
cpp = '#4889D4'

[palettes.eva01]
white = '#DFDFDF'
green = '#27C722'
red   = '#CF2727'
bg_base = '#404040'
fg_os = '#DFDFDF'
bg_os = '#202020'
fg2 = '#202020'
bg2 = '#27C722'
fg3 = '#DFDFDF'
bg3 = '#601BAB'
fg_cmd = '#202020'
bg_cmd = '#EB8900'
fg_cpu = '#EB8900'
bg_cpu = '#202020'
right_accent = '#EB8900'

git = '#3261E6'
cpp = '#4889D4'

[palettes.eva03]
white = '#DFDFDF'
green = '#27C722'
red   = '#CF2727'
bg_base = '#404040'
fg3 = '#DFDFDF'
bg3 = '#000F40'
fg2 = '#202020'
bg2 = '#DADADA'
bg_os = '#800000'
fg_cmd = '#202020'
bg_cmd = '#EB8900'
fg_cpu = '#EB8900'
bg_cpu = '#202020'
right_accent = '#EB8900'
fg_os = '#101010'
git = '#3261E6'
cpp = '#4889D4'

[palettes.eva06]
white = '#DFDFDF'
green = '#27C722'
red   = '#CF2727'
bg_base = '#404040'
fg3 = '#DFDFDF'
bg3 = '#174278'
fg2 = '#202020'
bg2 = '#D48E00'
bg_os = '#202020'
fg_cmd = '#202020'
bg_cmd = '#EB8900'
fg_cpu = '#EB8900'
bg_cpu = '#202020'
right_accent = '#EB8900'
fg_os = '#101010'
git = '#3261E6'
cpp = '#4889D4'
